language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

# install codecov
before_install:
  - pip install codecov

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - coverage run run_unittest.py

after_success:
  - codecov
